title: "Merging Data"
author:
- Arushi Agarwal
date: '7/22/2022'
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
    number_sections: yes
  pdf_document:
    toc_depth: '4'
    number_sections: yes
urlcolor: blue
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T, fig.width=6, fig.height=3)
options(scipen = 0, digits = 3)  # controls base R output
if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(glmnet, leaps, car, tidyverse, pROC, caret, data.table)
```

```{r reading}
censusdata <- fread("data/counties.csv")
crimedata <- fread("data/crime/crime17.csv")
```

```{r cleaning}
to_delete <- "(county|census area|borough|municipality)"
censusdata <- censusdata %>%
        rename(county = name) %>%
        mutate(county = sub(to_delete, "", tolower(county)) %>% trimws(),
               state = tolower(state),
               statecounty = paste(state, county))

crimedata <- crimedata %>%
        mutate(county = tolower(county),
               state = tolower(state),
               statecounty = paste(state, county))

data <- full_join(censusdata, crimedata, by="statecounty") %>%
        rename(state = state.x, county = county.x) %>%
        select(-c(state.y, county.y, statecounty)) %>%
        select(state, county, everything()) %>%
        drop_na()

write.csv(data, "data/data.csv", row.names = FALSE)
```
